---
- name: Clear All Access config
  hosts: access
  connection: network_cli

- name: Clear All Core config
  hosts: core
  tags: core
  connection: network_cli
  tasks:
    - import_tasks: "tasks/erase_config.yml"
      vars:
        INTERFACES: "{{interfaces[inventory_hostname] +
                      core_l3_links[inventory_hostname] +
                      svi_interfaces }}"
        VLANS: "{{ vlans + core_vlans }}"
