- name: "PLAY 3: Configure WAN Routers"
  hosts: wan
  tags: wan
  tasks:
    - name: "P3T1: Configure System parameters"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"

    - name: "P3T2: Configure NTP"
      ios_ntp:
        server: "{{ ntp_server }}"
        logging: true
        source_int: GigabitEthernet2
        state: present

    - name: "P3T2: Configure Managment Static Routes"
      ios_static_route:
        prefix: "{{ item.prefix.split('/')[0] }}"
        mask: "{{ item.prefix | ipv4('netmask') }}"
        next_hop: "{{ item.next_hop }}"
      loop: "{{ mgmt_static_routes }}"

    - name: "P3T3: Configure All Interfaces"
      ios_interface:
        name: "{{ item.name }}"
        description: "{{ item.description | default('') }}"
        mtu: "{{ intf_mtu }}"
        state: up
      loop: "{{ wan_l3_links[inventory_hostname] }}"

    - name: "P3T4: Configure Interface IP Addresses"
      ios_l3_interface:
        name: "{{item.name }}"
        ipv4:  "{{item.ipv4 }}"
      loop: "{{wan_l3_links[inventory_hostname]}}"

