- name: "PLAY 2: Configure Core Switches"
  hosts: core
  tags: l3_core
  tasks:

    - name: "P2T1: Create L2 Core VLANs"
      ios_vlan:
        vlan_id : "{{item.vlan_id | int}}"
        interfaces: "{{ item.interface}}"
      loop: "{{ core_vlans }}"
      tags: vlan

    - name: "P2T2: Allow Core VLANs on Core Trunk"
      ios_l2_interface:
        name: "{{ item.interface }}"
        mode: trunk
        trunk_allowed_vlans: "{{ (vlans + core_vlans) |
                                  map(attribute='vlan_id') |
                                  join(',') }}"
        state: present
      loop: "{{ core_vlans }}"

    - name: "P2T3: Adjust VLAN Priority"
      ios_config:
        lines:
          - spanning-tree vlan {{ item.vlan_id }} priority {{ hst_vlan_priority }}
      loop: "{{(vlans + core_vlans) }}"
      tags: spt

    - name: "P2T1: Create L3 VLAN Interfaces"
      ios_l3_interface:
        name: "{{item.name }}"
        ipv4:  "{{item.ipv4 | ipv4(hst_svi_id)}}"
      loop: "{{svi_interfaces}}"
      tags: l3_svi

    - name: "P2T2: Enable the VLAN Interfaces"
      ios_interface:
        name: "{{ item.name }}"
        state: up
      loop: "{{ svi_interfaces }}"

    - name: "P2T3: Create VRRP Configs"
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - vrrp {{item.name.split('Vlan')[1]}} priority {{ hst_vrrp_priority }}
          - vrrp {{item.name.split('Vlan')[1]}} ip {{item.ipv4 | ipv4(254)|ipaddr('address')}}
      loop: "{{svi_interfaces | selectattr('vrrp','equalto',true) | list }}"

    - name: "P2T4: Create WAN Links"
      ios_interface:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        duplex: "{{ intf_duplex }}"
        mtu: "{{ intf_mtu }}"
        state: up
      when: "'Loopback0' not in item.name"
      loop: "{{ core_l3_links[inventory_hostname] }}"


    - name: "P2T5: Make Wan Interfaces as L3 Interfaces"
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - no switchport
        save_when: changed
      loop: "{{core_l3_links[inventory_hostname]}}"
      when: "'Loopback0' not in item.name"

    - name: "P2T6: Configure IP Address on WAN Links"
      ios_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 | ipv4(1) }}"
      loop: "{{ core_l3_links[inventory_hostname] }}"
      when: "'Loopback0' not in item.name"

    - name: "P2T6: Configure IP Address on Loopback"
      ios_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
      loop: "{{ core_l3_links[inventory_hostname] }}"
      when: "'Loopback0' in item.name"
      tags: lo0

    - name: "P2T8: Configure OSPF"
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines:
          - router-id {{ loopback_prefix | ipv4(hst_router_id) | ipaddr('address')}}

    - name: "P2T9: Configure OSPF On Interfaces"
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - ip ospf {{ ospf_process }} area {{ ospf_area }}
          - ip ospf network point-to-point
          - ip ospf cost {{item.ospf_metric | default(ospf_metric)}}
      loop: "{{ (svi_interfaces + core_l3_links[inventory_hostname]) | selectattr('ospf') | list }}"

    - name: "P2T10: Configure OSPF Passive Interfaces"
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines: passive-interface {{item.name}}
      loop: "{{ (svi_interfaces + core_l3_links[inventory_hostname]) | selectattr('ospf','equalto','passive') | list }}"

